# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: shoplt
    devtools:
        restart:
            enabled: true
    cache:
        type: simple
    datasource:
        url: jdbc:mysql://${database.uri:localhost:3306}/${database.schema:shoplt}?useSSL=false&serverTimezone=UTC
        username: ${database.user:admin}
        password: ${database.password:admin}
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: SELECT 1
        testWhileIdle: true    
        tomcat:
            minIdle: ${database.minIdle:4}        
            maxIdle: ${database.maxIdle:8}
            maxActive: ${database.maxActive:10}
            initialSize: ${database.initialSize:4}
    jpa:
        show-sql: true
        hibernate.ddl-auto: update
        database-platform: org.hibernate.dialect.MySQL5Dialect        
        open-in-view: false
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
        cache: false
output.ansi.enabled : DETECT
logging:
    file: logs/shoplt.log
    pattern:
        console: "%clr([%d{yyyy-MM-dd HH:mm:ss,SSS}]){green} %highlight([%-5level]) %cyan([%-30c{1}]) - %m%n"
        file: "[%d{yyyy-MM-dd HH:mm:ss,SSS}][%-5level][%-30c{1}] %m%n"
#    level:
#        org.springframework: DEBUG
#        org.hibernate: DEBUG

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias jh_test -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        key-store-type: PKCS12
#        key-alias: jh_test
# ===================================================================
server:
    port: 8080
